channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip:
      - git+https://github.com/joshmoore/linkml.git@subclass-info
      - git+https://github.com/joshmoore/linkml-runtime.git@subclass-info
