#title: Genes list linked through pathways on triple-negative breast cancer
PREFIX wd:<http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase:<http://wikiba.se/ontology#>
PREFIX bd:<http://www.bigdata.com/rdf#>

SELECT DISTINCT ?gene ?geneLabel WHERE {
    VALUES ?disease {wd:Q7843332} # with a main subject of triple negative breast cancer
    ?pathway wdt:P2410 ?wpid ;      # pathways with a Wikipathways ID
             wdt:P921 ?disease ;
             wdt:P527 ?gene .      # which has various parts
    ?gene wdt:P31 wd:Q7187 .       # part is of part gene
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
