## genes associated with non-healthy images part of data set HPA040725
SELECT DISTINCT ?image ?gene ?disease WHERE {
  ?image dcterms:isPartOf hpa:HPA040725 ;
         wdt:P180 [ wdt:P353 ?gene ];
         wdt:P180 [ wdt:P1050 ?disease ]
  FILTER( ?disease != <http://purl.bioontology.org/ontology/SNMI/M-00100>) # normal tissue
} limit 100
