PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX hpa: <http://www.proteinatlas.org/search/>

## genes associated with non-healthy images
SELECT DISTINCT ?gene (count(?disease) as ?diseases) WHERE {
  ?image 
         wdt:P180 [ wdt:P353 ?gene ];
         wdt:P180 [ wdt:P1050 ?disease ]
  FILTER( ?disease != <http://purl.bioontology.org/ontology/SNMI/M-00100>)
} group by ?gene limit 50
