PREFIX sio: <http://semanticscience.org/resource/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?subject ?identifier ?background ?backgroundLabel
WHERE {
  ?subject rdf:type obo:NCIT_C16960 ;
           dcterms:identifier ?identifier ;
           obo:RO_0000053 ?subject_properties .

  ?subject_properties sio:SIO_000223 ?background .

  ?background rdfs:label ?backgroundLabel .
}

